name = "Beyond the Horizon"
author = "BTH Team"
version = "1.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b9905ba826b70539cc9004a7cd3b1ee3845f15bbd38b4079ff1c22517e4f963"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
