name = "Beyond the Horizon"
author = "BTH Team"
version = "1.12.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b084367d4aa0acc9373bcd2601a66e27d253c90419f1e7c0bb2f3d16145db168"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
