name = "Beyond the Horizon"
author = "BTH Team"
version = "1.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0561a957484302457af19f8031141142503ed69d222f03f0e8686074c0c765be"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
