name = "Beyond the Horizon"
author = "BTH Team"
version = "1.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a2dc240f96850c11c5e1e31931efca75b9b6210b8a1171f7ef40a92d2276e8d"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
